# ELO Scores

## Objective

Add the 2026 starting ELO score to each 2026 World Cup team. I use the distance dataset created in this folder and join only the `WC_2026` ELO score from `ELOStartRatings.csv`.

## Inputs

- `1.DataCleaning-R/Data/RDS/WC2026DistanceFromHost.rds`
- `1.DataCleaning-R/Data/CSV/ELOStartRatings.csv`

## Output

- `1.DataCleaning-R/Data/RDS/WC2026DistanceELO.rds`

## Acknowledgments

ELO data is taken from eloratings.net.

## Libraries

In [38]:
library(here)
library(tidyverse)

## Load Data

The distance dataset already contains one row for each 2026 World Cup team.

In [39]:
distance_from_host <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "WC2026DistanceFromHost.rds"))

elo_scores <- read.csv(here("1.DataCleaning-R", "Data", "CSV", "ELOStartRatings.csv")) %>%
    select(elo_team = team, elo_2026 = WC_2026)

distance_from_host %>% count(tournament_id)
elo_scores %>% slice_sample(n = 5)

  tournament_id n
1 WC-2026       48

  elo_team elo_2026
1 Denmark  1864
2 Sweden   1660
3 Colombia 1998
4 Italy    1859
5 Scotland 1790

## Match Team Names

A few country names need to match the names used in the ELO file.

In [40]:
elo_name <- function(country) {
    case_when(
        country == "Cabo Verde" ~ "Cape Verde",
        country == "Congo DR" ~ "DR Congo",
        TRUE ~ country
    )
}

distance_elo_names <- distance_from_host %>%
    mutate(elo_team = elo_name(team_name))

distance_elo_names %>%
    anti_join(elo_scores, by = "elo_team") %>%
    select(team_name, team_code, elo_team)

     team_name team_code elo_team

## Add ELOs

Only the 2026 starting ELO score is added. Attack and defence ELOs are not included.

In [41]:
distance_elo <- distance_elo_names %>%
    left_join(elo_scores, by = "elo_team") %>%
    select(
        tournament_id,
        team_name,
        team_id,
        team_code,
        host_country,
        is_home_country,
        country_lat,
        country_long,
        host_lat,
        host_long,
        distance_from_host_km,
        elo_2026
    ) %>%
    arrange(team_name)

distance_elo %>%
    summarize(
        teams = n(),
        missing_elo = sum(is.na(elo_2026)),
        min_elo = min(elo_2026, na.rm = TRUE),
        max_elo = max(elo_2026, na.rm = TRUE),
        .groups = "drop"
    )

  teams missing_elo min_elo max_elo
1 48    0           1425    2172

In [42]:
distance_elo <- distance_elo %>%
    select(team_name, team_id, team_code, distance_from_host_km, elo_2026)

distance_elo

   team_name              team_id team_code distance_from_host_km elo_2026
1  Algeria                T-01    DZA        8467.886             1757
2  Argentina              T-03    ARG        9076.351             2113
3  Australia              T-04    AUS       14653.989             1774
4  Austria                T-05    AUT        8351.637             1818
5  Belgium                T-06    BEL        7608.706             1850
6  Bosnia and Herzegovina T-08    BIH        8799.915             1572
7  Brazil                 T-09    BRA        7396.652             1978
8  Cabo Verde             NA      CPV        7732.128             1561
9  Canada                 T-12    CAN           0.000             1802
10 Colombia               T-16    COL        4836.620             1998
11 Congo DR               NA      COD       13091.614             1657
12 Croatia                T-18    HRV        8608.749             1932
13 Curacao                NA      CUW        4359.810             1466
14 Czechia                T-20    CZE        8250.287             1731
15 Ecuador                T-25    ECU        5050.644             1933
16 Egypt                  T-26    EGY       11013.883             1622
17 England                T-28    ENG        7152.496             2042
18 France                 T-30    FRA        7714.673             2062
19 Germany                T-31    DEU        7888.052             1910
20 Ghana                  T-32    GHA       10227.033             1509
21 Haiti                  T-34    HTI        3531.271             1542
22 Iran                   T-38    IRN       11560.024             1755
23 Iraq                   T-39    IRQ       11131.489             1582
24 Ivory Coast            T-42    CIV        9853.150             1627
25 Japan                  T-44    JPN        9562.527             1878
26 Jordan                 NA      JOR       10984.602             1689
27 Mexico                 T-46    MEX           0.000             1835
28 Morocco                T-47    MAR        8047.458             1840
29 Netherlands            T-48    NLD        7554.561             1959
30 New Zealand            T-49    NZL       12567.390             1585
31 Norway                 T-53    NOR        7116.619             1922
32 Panama                 T-54    PAN        3966.490             1742
33 Paraguay               T-55    PRY        8273.165             1833
34 Portugal               T-58    PRT        7492.663             1976
35 Qatar                  T-59    QAT       12201.517             1425
36 Saudi Arabia           T-63    SAU       11783.518             1592
37 Scotland               T-64    SCO        6752.840             1790
38 Senegal                T-65    SEN        8646.943             1807
39 South Africa           T-70    ZAF       14937.121             1550
40 South Korea            T-71    KOR       10196.189             1784
41 Spain                  T-73    ESP        7746.923             2172
42 Sweden                 T-74    SWE        7465.038             1660
43 Switzerland            T-75    CHE        8079.838             1897
44 Tunisia                T-79    TUN        9114.638             1615
45 Turkey                 T-80    TUR       10136.437             1880
46 United States          T-83    USA           0.000             1747
47 Uruguay                T-84    URY        9282.411             1890
48 Uzbekistan             NA      UZB       10859.455             1735

Manually compare to website

In [44]:
set.seed(2026)
distance_elo %>%
    slice_sample(n=5)

  team_name   team_id team_code distance_from_host_km elo_2026
1 Netherlands T-48    NLD        7554.561             1959
2 Paraguay    T-55    PRY        8273.165             1833
3 Senegal     T-65    SEN        8646.943             1807
4 Turkey      T-80    TUR       10136.437             1880
5 Mexico      T-46    MEX           0.000             1835

All good!

## Save

In [43]:
saveRDS(distance_elo, here("1.DataCleaning-R", "Data", "RDS", "WC2026DistanceELO.rds"))