# ELO Scores

## Objectives

Develop a dataset with ELO Scores for each nation in the 2010, 2014, 2018, 2022, and 2026 World Cups. I'm using the ELO scores on Dec 31 the year prior to the world cup. This decision is based on accesibility and consistency. I could not find a reliable way to exctract all ELO scores for each nation at the same date for every world cup at any closer date. I believe it is both a more honest approach and more reliable to set a standard date for all world cups than just using the best date I could find for each tournament. I also compared the ELO scores manually between Dec 31 and datys before the world cup and the differences are minimal.
- Columns: team, WC_2026, WC_2022, WC_2018, WC_2014, WC_2010.
- Rows: One per team that has participated in any of the last 4 world cups.

## Inputs

- `1.DataCleaning-R/Data/RDS/FullTeamGames.rds`
- `1.DataCleaning-R/Data/CSV/ELOStartRatings.csv`
-`1.DataCleaning-R/Data/CSV/ELOAttackDefence.csv`

## Output

- `1.DataCleaning-R/Data/RDS/ELOScores.rds`
- `1.DataCleaning-R/Data/RDS/ATTvsDEF.rds`

## Acknowledgments

Data in this notebook is taken from eloratings.net and https://www.international-football.net/

## Libraries

In [34]:
library(here)
library(tidyverse)

## Scrape ELO Scores

In [35]:
FullRoster <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullTeamGames.rds"))
unique(FullRoster$team_name)

 [1] "Algeria"                "Argentina"              "Australia"
 [4] "Brazil"                 "Cameroon"               "Chile"
 [7] "Denmark"                "England"                "France"
[10] "Germany"                "Ghana"                  "Greece"
[13] "Honduras"               "Italy"                  "Ivory Coast"
[16] "Japan"                  "Mexico"                 "Netherlands"
[19] "New Zealand"            "Nigeria"                "North Korea"
[22] "Paraguay"               "Portugal"               "Serbia"
[25] "Slovakia"               "Slovenia"               "South Africa"
[28] "South Korea"            "Spain"                  "Switzerland"
[31] "United States"          "Uruguay"                "Belgium"
[34] "Bosnia and Herzegovina" "Colombia"               "Costa Rica"
[37] "Croatia"                "Ecuador"                "Iran"
[40] "Russia"                 "Egypt"                  "Iceland"
[43] "Morocco"                "Panama"                 "Peru"
[46] "Poland"                 "Saudi Arabia"           "Senegal"
[49] "Sweden"                 "Tunisia"                "Canada"
[52] "Qatar"                  "Wales"

I used https://www.eloratings.net/ to retrieve ELO scores for all the teams. I couldn't find any APIs or options to download the data. I used Codex AI (by OPENAI) to automate the process. I instructed Codex to go through the data in teh website to get the specific data in the specific tabular format I wanted. I then instructed it to save this data as a csv on my data folder. Now I will manually check random data points to ensure the scores are accurate, making sure to check a representative sample.

In [36]:
set.seed(2026)

ELOScores <- read.csv(here("1.DataCleaning-R", "Data", "CSV", "ELOStartRatings.csv"))
ELOScores %>% 
    slice_sample(n=5)

  team    WC_2026 WC_2022 WC_2018 WC_2014 WC_2010
1 Iran    1755    1837    1800    1732    1634
2 Peru    1707    1834    1881    1711    1587
3 Panama  1742    1627    1670    1699    1550
4 Brazil  1978    2149    2113    2132    2103
5 Iceland 1566    1546    1811    1542    1446

They are accurate!

Lets work on the Attack vs Defence ELOs.

In [37]:
set.seed(2026)
ELOATTvsDEF <- read.csv(here("1.DataCleaning-R", "Data", "CSV", "ELOAttackDefence.csv"))

ELOATTvsDEF %>%
    slice_sample(n=5)

  team_name   tournament_id attack defence
1 Serbia      WC-2022        87     63
2 Brazil      WC-2014       117    102
3 England     WC-2014        75     77
4 Iran        WC-2022        73     73
5 South Korea WC-2018        59     71

After manual inspection they all match the source data!

In [38]:
saveRDS(ELOScores, here("1.DataCleaning-R", "Data", "RDS", "ELOSScores.rds"))
saveRDS(ELOATTvsDEF, here("1.DataCleaning-R", "Data", "RDS", "ELOATTvsDEF.rds"))