# Players per team per tournament

## Objectives 

Develop a structured dataset with a comprehensive list of all players that were called to each team per tournament.

- Columns: tournament_id, team_name, team_id, team_code, player_id, family_name, given_name, position_code.
- Rows: One per player per tournament (meaning players may be repeated if they participated in multiple world cups).

## Acknowledgments

I used data from The Fjelstul World Cup Database throught the R Package "worldcup". 
About The Fjelstul World Cup Database:
- Author: Joshua C. Fjelstul, Ph.D.
- Copyright: © 2023 Joshua C. Fjelstul, Ph.D.
- License: https://creativecommons.org/licenses/by-sa/4.0/legalcode
- GitHub: https://github.com/jfjelstul/worldcup


## Packages

In [18]:
library(tidyverse)
library(worldcup)
library(here)

## Rosters

In [1]:
FullRoster <- worldcup::squads
colnames(FullRoster)

 [1] "key_id"          "tournament_id"   "tournament_name" "team_id"
 [5] "team_name"       "team_code"       "player_id"       "family_name"
 [9] "given_name"      "shirt_number"    "position_name"   "position_code"

 [1] "WC-1930" "WC-1934" "WC-1938" "WC-1950" "WC-1954" "WC-1958" "WC-1962"
 [8] "WC-1966" "WC-1970" "WC-1974" "WC-1978" "WC-1982" "WC-1986" "WC-1990"
[15] "WC-1991" "WC-1994" "WC-1995" "WC-1998" "WC-1999" "WC-2002" "WC-2003"
[22] "WC-2006" "WC-2007" "WC-2010" "WC-2011" "WC-2014" "WC-2015" "WC-2018"
[29] "WC-2019" "WC-2022"

In [20]:
FullRoster <- FullRoster %>%  
    filter(as.numeric(str_sub(tournament_id, -4)) >= 2010) %>%
        filter(!(tournament_id %in% c("WC-2015", "WC-2019", "WC-2011")))

dim(FullRoster)

[1] 3039   12

The dataset description doesnt tell us the specifics of the squads. I'm interested in knowing wether each team had the same amount of players.

In [21]:
FullRoster %>% group_by(tournament_id, team_name) %>%
    summarise(players = sum(n())) %>%
        slice_sample(n=3)

`summarise()` has grouped output by 'tournament_id'. You can override using the
`.groups` argument.

   tournament_id team_name   players
1  WC-2010       North Korea 23
2  WC-2010       Netherlands 23
3  WC-2010       South Korea 23
4  WC-2014       Greece      23
5  WC-2014       Mexico      23
6  WC-2014       Japan       23
7  WC-2018       South Korea 23
8  WC-2018       Denmark     23
9  WC-2018       Japan       23
10 WC-2022       Spain       26
11 WC-2022       Iran        25
12 WC-2022       Croatia     26

We can see 2010-2018 tournaments had 23 players on each squad while 2022 had 26.

In [ ]:
FullRoster <- FullRoster %>% 
    select(tournament_id, team_name, team_id, team_code, player_id, family_name, given_name, position_code) %>%
        mutate(full_name = paste(given_name, family_name))

FullRoster %>%
    select(full_name) %>%
        slice_sample(n=5)

  full_name
1 Mohamed Salah
2 Jeremain Lens
3 not applicable Juan
4 <U+00C1>lvaro Zamora
5 Dar<U+00ED>o Ver<U+00F3>n

In [23]:
saveRDS(FullRoster, here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds"))