# World Cup Schedules and Results

## Objective

In this notebook I want to create a dataset with the following structure:

- Columns: tournament_id, stage_name, group_stage, goals_against, goals_for, team_id, opponent_id, city_name, team_name, opponent_name.
- Rows: All games in the 2010, 2014, 2018, and 2022 World Cup. That is 512 rows since there is 64 games per WC and we have 2 rows per game (one per team), hence: 64*4*2=512.

This dataset will be the bases for our training data to fit our regression model to estimate our rate parameter of our Poisson Distirbution.

Why start at 2010? I'm planning on using player ratings provided by websites liek SofaScore, FotMob, and WhoScored as part of our explanatory infrastructure. The earliest ratings I could find are from 2009/2010 season. 

## Acknowledgments

I used data from The Fjelstul World Cup Database throught the R Package "worldcup". 
About The Fjelstul World Cup Database:
- Author: Joshua C. Fjelstul, Ph.D.
- Copyright: © 2023 Joshua C. Fjelstul, Ph.D.
- License: https://creativecommons.org/licenses/by-sa/4.0/legalcode
- GitHub: https://github.com/jfjelstul/worldcup

## Packages

In [ ]:
library(tidyverse)
library(worldcup)
library(here)

## Hisotrical World Cup Records

In [34]:
FullTeamGames <- worldcup::team_appearances
head(FullTeamGames)
colnames(FullTeamGames)

  key_id tournament_id tournament_name           match_id
1 1      WC-1930       1930 FIFA Men's World Cup M-1930-01
2 2      WC-1930       1930 FIFA Men's World Cup M-1930-01
3 3      WC-1930       1930 FIFA Men's World Cup M-1930-02
4 4      WC-1930       1930 FIFA Men's World Cup M-1930-02
5 5      WC-1930       1930 FIFA Men's World Cup M-1930-03
6 6      WC-1930       1930 FIFA Men's World Cup M-1930-03
  match_name               stage_name  group_name group_stage knockout_stage
1 France vs Mexico         group stage Group 1    1           0
2 France vs Mexico         group stage Group 1    1           0
3 United States vs Belgium group stage Group 4    1           0
4 United States vs Belgium group stage Group 4    1           0
5 Yugoslavia vs Brazil     group stage Group 2    1           0
6 Yugoslavia vs Brazil     group stage Group 2    1           0
  replayed ... goals_against goal_differential extra_time penalty_shootout
1 0        ... 1              3                0          0
2 0        ... 4             -3                0          0
3 0        ... 0              3                0          0
4 0        ... 3             -3                0          0
5 0        ... 1              1                0          0
6 0        ... 2             -1                0          0
  penalties_for penalties_against result win lose draw
1 0             0                 win    1   0    0
2 0             0                 lose   0   1    0
3 0             0                 win    1   0    0
4 0             0                 lose   0   1    0
5 0             0                 win    1   0    0
6 0             0                 lose   0   1    0

 [1] "key_id"            "tournament_id"     "tournament_name"
 [4] "match_id"          "match_name"        "stage_name"
 [7] "group_name"        "group_stage"       "knockout_stage"
[10] "replayed"          "replay"            "match_date"
[13] "match_time"        "stadium_id"        "stadium_name"
[16] "city_name"         "country_name"      "team_id"
[19] "team_name"         "team_code"         "opponent_id"
[22] "opponent_name"     "opponent_code"     "home_team"
[25] "away_team"         "goals_for"         "goals_against"
[28] "goal_differential" "extra_time"        "penalty_shootout"
[31] "penalties_for"     "penalties_against" "result"
[34] "win"               "lose"              "draw"

In [35]:
FullTeamGames <- FullTeamGames %>%  
    select(tournament_id, stage_name, group_stage, goals_against, goals_for, team_id, opponent_id, city_name, team_name, opponent_name)

dim(FullTeamGames)

[1] 2496   10

In [36]:
FullTeamGames <- FullTeamGames %>%
    filter(as.numeric(str_sub(tournament_id, -4)) >= 2010)

dim(FullTeamGames)

[1] 784  10

After filtering tournaments we still have more rows than expected. Lets inspect this.

In [37]:

FullTeamGames %>% 
    group_by(tournament_id) %>%
        summarize(games = sum(n()))

  tournament_id games
1 WC-2010       128
2 WC-2011        64
3 WC-2014       128
4 WC-2015       104
5 WC-2018       128
6 WC-2019       104
7 WC-2022       128

The issue here is that we have Women's and Men's world cup data. For this particular dataset we're only interested in Men's world cups.

In [40]:
FullTeamGames <- FullTeamGames %>%
    filter(!(tournament_id %in% c("WC-2015", "WC-2019", "WC-2011")))

dim(FullTeamGames)

[1] 512  10

In [41]:
saveRDS(FullTeamGames, here("1.DataCleaning-R", "Data", "RDS", "FullTeamGames.rds"))